---
title: "ENV623_Final_Project"
author: "Sameer, Josh, Graham"
date: '2025-04-13'
output: pdf_document
---

```{r clear-project}
rm(list=ls())
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import-libraries}
library(dplyr)
library(readxl)
library(tidyr)
library(tibble)
library(hdm)
library(stringr)

load("./climate_data/monthlyClimateKruger.rdata")
```

```{r import-elephant}

e_dat <- read.csv("./wildlife_insights_data/images_2009198.csv")
deployments_dat <- read.csv("./wildlife_insights_data/deployments.csv")

e_dat |>
  summarise(
    n_proboscidea = sum(order == "Proboscidea"),
    n_elephantidae = sum(family == "Elephantidae"),
    n_loxodonta = sum(genus == "Loxodonta"),
    n_loxodonta_africana = sum(species == "africana")
  ) |>
  print()

# Proboscidae is sufficent to guarantee African elephant, and
# As we can see, some datapoints are not sufficiently labeled
e_dat <- e_dat[e_dat$order == "Proboscidea", ]
e_dat <- e_dat[, c("deployment_id", "location", "timestamp", "number_of_objects")]

deployments_dat <- deployments_dat[, c("deployment_id", "placename", "longitude", "latitude", "start_date", "end_date", "camera_id", "camera_name")]

# Convert to time format
e_dat$timestamp <- as.POSIXct(e_dat$timestamp, format = "%Y-%m-%d %H:%M:%S")
str(e_dat$timestamp)

deployments_dat$start_date <- as.POSIXct(deployments_dat$start_date, format = "%Y-%m-%d %H:%M:%S")
deployments_dat$end_date <- as.POSIXct(deployments_dat$end_date, format = "%Y-%m-%d %H:%M:%S")
str(deployments_dat$end_date)
str(deployments_dat$start_date)

#site_counts <- e_dat |>
#  count(deployment_id)

deployments_dat$days <- round(as.numeric(deployments_dat$end_date - deployments_dat$start_date, units = "days"))


site_counts <- e_dat |>
  group_by(deployment_id) |>
  summarise(
    counts = sum(number_of_objects, na.rm = TRUE),
    counts_f21 = sum(number_of_objects[timestamp >= as.POSIXct("2025-02-21")], na.rm = TRUE)
  )

deployments_dat <- deployments_dat |>
  left_join(site_counts, by = "deployment_id") |>
  mutate(
    counts = coalesce(counts, 0),
    counts_f21 = coalesce(counts_f21, 0)
  )

deployments_dat$norm_counts <- deployments_dat$counts / deployments_dat$days
deployments_dat$norm_counts_f21 <- deployments_dat$counts_f21 / min(deployments_dat$days, na.rm = TRUE)



# Print totals
print(sum(deployments_dat$num_elephants, na.rm = TRUE))
print(sum(deployments_dat$num_elephants_f21, na.rm = TRUE))

```

```{r site-data}
# check if latitude and longitude is the same between deployments
deployments_dat |>
  group_by(placename) |>
  summarise(
    n_long = n_distinct(longitude),
    n_lat = n_distinct(latitude)
  ) |>
  filter(n_long > 1 | n_lat > 1)

# For the days, each site's deployments had exactly the same number of days so the code works correctly.
# DO NOT CHANGE THE ORDER OF THIS PLS
site_dat <- deployments_dat |>
  group_by(placename, longitude, latitude) |>
  summarise(
    num_deployments = n(),
    total_days = sum(days, na.rm = TRUE),
    total_days_f21 = num_deployments*(19),
    days = min(days, na.rm = TRUE),
    days_f21 = 19,
    total_counts = sum(counts, na.rm = TRUE),
    total_counts_f21 = sum(counts_f21, na.rm = TRUE),
    norm_counts = total_counts / total_days,
    norm_counts_f21 = total_counts_f21 / total_days_f21,
    .groups = "drop"
  )

```


```{r}
# rm(e_dat_filtered)
testing_e_dat <- read.csv("./wildlife_insights_data/images_2009198.csv")
# table(testing_dat$identified_by)

```

```{r}
table(e_dat$deployment_id)

table(deployments_dat$start_date)

table(deployments_dat$end_date)

table((deployments_dat$placename))

# Elephant Presence by location
intersect(unique(e_dat$placename), unique(deployments_dat$placename))
setdiff(unique(deployments_dat$placename), unique(e_dat$placename))

# Elephant Presence by camera site
intersect(unique(e_dat$deployment_id), unique(deployments_dat$deployment_id))
setdiff(unique(deployments_dat$deployment_id), unique(e_dat$deployment_id))
```

```{r}
#Import iNaturalist data on trees
iNat <- read.csv("./ENV 623 - iNaturalist Observations.csv")
```

```{r}
#Define function to translate site name to placename
translate_code <- function(codes) {
  # Match: VRP<prefix>_<optional R><number><optional R>
  matches <- str_match(codes, "VRP(.*?)(?:_R|_)?(\\d+)(R)?")
  
  prefix <- matches[, 2]       # text after VRP
  number <- matches[, 3]       # digits
  paste0(prefix, "_", number, "R")
}
```

```{r}
#Filter to relevant columns and only trees
#Select rows where crown diameter is NA so it is only trees
tree_data <- iNat %>%
             filter(is.na(field.crownradius)) %>%
             select(latitude, longitude, species_guess, scientific_name, common_name, field.stemdiameter, field.treeidentifier) %>%
             mutate(field.treeidentifier = toupper(field.treeidentifier)) %>%
             mutate(site_name = translate_code(field.treeidentifier))
```

```{r}
#Read in and clean monthly precipitation data
prec_df <- as.data.frame(prec)

prec_df <- prec_df %>%
  rownames_to_column(var = "location")

prec_clean <- prec_df %>%
  mutate(
    location = gsub("^E", "", location),        # remove leading 'E'
    location = gsub("_N=|_N", "_", location)    # convert '_N=26' or '_N26' into '_26'
  ) %>%
  separate(location, into = c("longitude", "latitude"), sep = "_") %>%
  mutate(
    longitude = as.numeric(longitude),
    latitude = as.numeric(latitude)
  ) %>%
  mutate(latitude_1_dp = round(latitude, 1),
                    longitude_1_dp = round(longitude, 1)) %>%
  group_by(latitude_1_dp, longitude_1_dp) %>%
  summarise(avg_2023_03_prec = mean(`2023_03`, na.rm = TRUE)) %>%
  select(latitude_1_dp, longitude_1_dp, avg_2023_03_prec)

```

```{r}
#Read in and clean monthly temperature data
temp_df <- as.data.frame(temp)

temp_df <- temp_df %>%
  rownames_to_column(var = "location")

temp_clean <- temp_df %>%
  mutate(
    location = gsub("^E", "", location),        # remove leading 'E'
    location = gsub("_N=|_N", "_", location)    # convert '_N=26' or '_N26' into '_26'
  ) %>%
  separate(location, into = c("longitude", "latitude"), sep = "_") %>%
  mutate(
    longitude = as.numeric(longitude),
    latitude = as.numeric(latitude)
  ) %>%
  mutate(latitude_1_dp = round(latitude, 1),
                    longitude_1_dp = round(longitude, 1)) %>%
  group_by(latitude_1_dp, longitude_1_dp) %>%
  summarise(avg_2023_03_temp = mean(`2023_03`, na.rm = TRUE)) %>%
  select(latitude_1_dp, longitude_1_dp, avg_2023_03_temp)

```

```{r}
#Read in and clean monthly temperature data
pet_df <- as.data.frame(pet)

pet_df <- pet_df %>%
  rownames_to_column(var = "location")

pet_clean <- pet_df %>%
  mutate(
    location = gsub("^E", "", location),        # remove leading 'E'
    location = gsub("_N=|_N", "_", location)    # convert '_N=26' or '_N26' into '_26'
  ) %>%
  separate(location, into = c("longitude", "latitude"), sep = "_") %>%
  mutate(
    longitude = as.numeric(longitude),
    latitude = as.numeric(latitude)
  ) %>%
  mutate(latitude_1_dp = round(latitude, 1),
                    longitude_1_dp = round(longitude, 1)) %>%
  group_by(latitude_1_dp, longitude_1_dp) %>%
  summarise(avg_2023_03_pet = mean(`2023_03`, na.rm = TRUE)) %>%
  select(latitude_1_dp, longitude_1_dp, avg_2023_03_pet)

```

```{r}
#Left join temp, prec to tree data on lat and long 
tree_final <- tree_data %>%
              mutate(latitude_1_dp = round(latitude, 1),
                    longitude_1_dp = round(longitude, 1)) %>%
              left_join(prec_clean, by = c("latitude_1_dp", "longitude_1_dp")) %>%
              left_join(temp_clean, by = c("latitude_1_dp", "longitude_1_dp")) %>%
              left_join(pet_clean, by = c("latitude_1_dp", "longitude_1_dp"))
```

```{r}
# Final Dataframe
site_dat <- site_dat |>
  mutate(placename = toupper(placename))

tree_final <- tree_final |>
  mutate(site_name = toupper(site_name))

d <- tree_final |>
  left_join(site_dat, by = c("site_name" = "placename"))

d <- d[, c("field.stemdiameter", "site_name", "avg_2023_03_prec", "avg_2023_03_temp", "avg_2023_03_pet", "norm_counts", "norm_counts_f21")]

d <- d |>
  filter(!is.na(norm_counts))

# Create Dummies
site_dummies <- model.matrix(~ site_name - 1, data = d)
colnames(site_dummies) <- sub("^site_name", "", colnames(site_dummies))

# Drop first column to prevent multicollinearity (Currently it is LTGRAN_10R)
site_dummies <- site_dummies[, -1, drop = FALSE]
d <- cbind(d, as.data.frame(site_dummies))
site_covs <- colnames(site_dummies)

# Remove unnecessary column
d <- select(d, -site_name)

# DEFINE REGRESSION VAR NAMES
W <- c("avg_2023_03_prec", "avg_2023_03_temp", "avg_2023_03_pet", site_covs)
Y <- "field.stemdiameter"
X <- "norm_counts"

```


```{r lasso-model}
# Y ~ X + W
# Y: Tree Diameter
# X: Elephant Counts
# W: Temperature, Precipitation, PET (Potential Evapotranspiration)

#########################
## Run LASSO Selection ##
#########################
all_predictors <- c(X, W)
formula_string <- paste(Y, "~", paste0("(", paste(all_predictors, collapse = " + "), ")^2"))

# Convert the string to a formula object
formula_obj <- as.formula(formula_string)

rlasso_model <- rlasso(formula_obj, data = d, post = FALSE)

lasso_coefs <- coef(rlasso_model)
selected_vars <- names(lasso_coefs)[lasso_coefs != 0]

selected_vars <- setdiff(selected_vars, "(Intercept)")

cat("Selected variables by rlasso (including interactions):\n")
print(selected_vars)

#######################################
## Use LASSO Covariates + norm_count ##
#######################################

selected_vars <- selected_vars[selected_vars != "(Intercept)"]

# Force norm_count to be in the regression
final_predictors <- union(X, selected_vars)
lm_formula_string <- paste(Y, "~", paste(final_predictors, collapse = " + "))
lm_formula <- as.formula(lm_formula_string)

cat("\nFormula for the final linear regression:\n")
print(lm_formula)

final_lm_model <- lm(lm_formula, data = d)

cat("\nSummary of the final linear regression model:\n")
print(summary(final_lm_model))

```



```{r}
#Mixed effects model: Tree Diameter ~ Elephant Presence + Site + Soil type + Temperature + Precipitation
# Variable effects: Soil Type, 


```

